import { DishCategoryType } from "@/types";

const categoriesForDishes: DishCategoryType[] = [
  {
    title: "Meat Dishes",
    slug: "meat",
    emoji: "🥩",
    description: "Mongolian meals packed with hearty, flavorful meats.",
    seoKeywords: [
      "Khuushuur",
      "Buuz",
      "Bansh",
      "Khorkhog",
      "Boodog",
      "Tsuivan",
      "Chanasan Makh",
      "Khar Khorum",
      "Shorlog",
      "Uuz",
      "Mongolian BBQ",
      "Mongolian Beef",
      "Mongolian Lamb",
    ],
  },
  {
    title: "Dairy Foods",
    slug: "dairy",
    emoji: "🥛",
    description: "Milk-based treats from cheese to fermented drinks.",
    seoKeywords: [
      "Aaruul",
      "Byaslag",
      "Tarag",
      "Airag",
      "Eezgii",
      "Urum",
      "Kefir",
      "Kumis",
      "Suutei Tsai",
      "Tsagaan Idee",
      "Mongolian Cheese",
      "Mongolian Yogurt",
      "Fermented Milk",
    ],
  },
  {
    title: "Breads & Dough",
    slug: "breads",
    emoji: "🍞",
    description: "Crispy, soft, and fried breads loved by Mongolians.",
    seoKeywords: [
      "Boortsog",
      "Gambir",
      "Khuushuur",
      "Borts",
      "Ul Boov",
      "Tsuivan",
      "Bansh",
      "Kheviin Boov",
      "Bortsog",
      "Khuushuur",
      "Mongolian Bread",
      "Fried Bread",
      "Mongolian Pastry",
    ],
  },
  {
    title: "Beverages",
    slug: "beverages",
    emoji: "🍹",
    description: "Traditional Mongolian drinks, from mild to strong.",
    seoKeywords: [
      "Airag",
      "Suutei Tsai",
      "Kumis",
      "Tarag",
      "Kefir",
      "Arkhi",
      "Milk Tea",
      "Boortsog",
      "Eezgii",
      "Urum",
      "Mongolian Tea",
      "Fermented Drink",
      "Mongolian Alcohol",
    ],
  },
  {
    title: "Soups & Stews",
    slug: "soups",
    emoji: "🍲",
    description: "Warm, rich broths perfect for cold weather.",
    seoKeywords: [
      "Bantan",
      "Guriltai Shul",
      "Tsuivan",
      "Boodog",
      "Khorkhog",
      "Chanasan Makh",
      "Shul",
      "Bansh",
      "Khuushuur",
      "Buuz",
      "Mongolian Soup",
      "Mongolian Stew",
      "Hearty Broth",
    ],
  },
  {
    title: "Exotic Foods",
    slug: "exotic",
    emoji: "🍖",
    description: "Unique and rare Mongolian specialty dishes.",
    seoKeywords: [
      "Boodog",
      "Khorkhog",
      "Khuushuur",
      "Buuz",
      "Bansh",
      "Chanasan Makh",
      "Tsuivan",
      "Shorlog",
      "Uuz",
      "Khar Khorum",
      "Mongolian Delicacy",
      "Traditional Dish",
      "Rare Food",
    ],
  },
];

export default categoriesForDishes;
