import { DishCategoryType } from "@/types";

const categoriesForDishes: DishCategoryType[] = [
  {
    title: "All Dishes",
    slug: "all",
    emoji: "🍖",
    description: "A comprehensive list of all Mongolian dishes.",
    seoKeywords: [
      "Khuushuur",
      "Buuz",
      "Bansh",
      "Khorkhog",
      "Boodog",
      "Tsuivan",
      "Chanasan Makh",
      "Khar Khorum",
      "Shorlog",
      "Uuz",
      "Mongolian BBQ",
      "Mongolian Beef",
      "Mongolian Lamb",
      "Aaruul",
      "Byaslag",
      "Tarag",
      "Airag",
      "Eezgii",
      "Urum",
      "Kefir",
      "Kumis",
      "Suutei Tsai",
      "Tsagaan Idee",
      "Mongolian Cheese",
      "Mongolian Yogurt",
      "Fermented Milk",
      "Boortsog",
      "Gambir",
      "Borts",
      "Ul Boov",
      "Kheviin Boov",
      "Mongolian Bread",
      "Fried Bread",
      "Mongolian Pastry",
      "Arkhi",
      "Milk Tea",
      "Mongolian Tea",
      "Fermented Drink",
      "Mongolian Alcohol",
      "Bantan",
      "Guriltai Shul",
      "Mongolian Soup",
      "Mongolian Stew",
      "Hearty Broth",
      "Mongolian Delicacy",
      "Traditional Dish",
      "Rare Food",
    ],
  },
  {
    title: "Meat Dishes",
    slug: "meat",
    emoji: "🥩",
    description: "Mongolian meals packed with hearty, flavorful meats.",
    seoKeywords: [
      "Khuushuur",
      "Buuz",
      "Bansh",
      "Khorkhog",
      "Boodog",
      "Tsuivan",
      "Chanasan Makh",
      "Khar Khorum",
      "Shorlog",
      "Uuz",
      "Mongolian BBQ",
      "Mongolian Beef",
      "Mongolian Lamb",
    ],
  },
  {
    title: "Dairy Foods",
    slug: "dairy",
    emoji: "🥛",
    description: "Milk-based treats from cheese to fermented drinks.",
    seoKeywords: [
      "Aaruul",
      "Byaslag",
      "Tarag",
      "Airag",
      "Eezgii",
      "Urum",
      "Kefir",
      "Kumis",
      "Suutei Tsai",
      "Tsagaan Idee",
      "Mongolian Cheese",
      "Mongolian Yogurt",
      "Fermented Milk",
    ],
  },
  {
    title: "Beverages",
    slug: "beverages",
    emoji: "🍹",
    description: "Traditional Mongolian drinks, from mild to strong.",
    seoKeywords: [
      "Airag",
      "Suutei Tsai",
      "Kumis",
      "Tarag",
      "Kefir",
      "Arkhi",
      "Milk Tea",
      "Boortsog",
      "Eezgii",
      "Urum",
      "Mongolian Tea",
      "Fermented Drink",
      "Mongolian Alcohol",
    ],
  },
  {
    title: "Soups",
    slug: "soups",
    emoji: "🍲",
    description: "Warm, rich broths perfect for cold weather.",
    seoKeywords: [
      "Bantan",
      "Guriltai Shul",
      "Tsuivan",
      "Boodog",
      "Khorkhog",
      "Chanasan Makh",
      "Shul",
      "Bansh",
      "Khuushuur",
      "Buuz",
      "Mongolian Soup",
      "Mongolian Stew",
      "Hearty Broth",
    ],
  },
];

export default categoriesForDishes;
