import { SeoType } from "@/types";

// This file contains the core meta data for the application
const seoConfig: SeoType = {
  title: "Mongolian Food",
  subTitle: " Mongolian food is hearty, bold, and full of surprises!",
  ogImage: "/images/opengraph-image.png",
  twitterImage: "/images/twitter-image.png",
  author: {
    name: "Tim Baz",
    twitterUrl: "https://x.com/timtbdev",
    twitterAddress: "@timtbdev",
    email: "timtb.dev@gmail.com",
  },
  description: "Top Mongolian dishes, recipes, and restaurants worldwide.",
  tags: [
    // Mongolian food must-tries
    "Mongolian food",
    "Meat lovers paradise",
    "Dumplings that slap",
    "Mongolian BBQ heaven",
    "Mongolian recipes",
    "Buuz: tiny pockets of happiness",
    "Khorkhog: meat cooked with rocks",
    "Boodog: whole animal, no problem",
    "Tsuivan: Mongolia’s take on noodles",
    "Mongolian dairy adventure",
    "Airag: milk that kicks back",
    "Fermented mare’s milk challenge",
    "Mongolian hot pot party",
    "Street food that won’t betray you",
    "How to eat like Genghis Khan",
    "Best Mongolian restaurants worldwide",

    // Where to eat Mongolian food worldwide
    "Where to eat Mongolian food",
    "Best Mongolian restaurants in Ulaanbaatar",
    "Mongolian BBQ in the USA",
    "Authentic Mongolian food in Europe",
    "Top Mongolian restaurants in Asia",
    "Mongolian food in New York",
    "Mongolian restaurants in Los Angeles",
    "Where to eat Mongolian BBQ in London",
    "Mongolian food guide for travelers",
    "Hidden gem Mongolian restaurants",
    "Mongolian street food markets",
    "Best places for Mongolian dumplings",
    "How to find real Mongolian food abroad",
    "Mongolian food near me",
    "Mongolian cuisine outside Mongolia",

    // Fun & quirky tags
    "Surviving Mongolia’s meat-heavy diet",
    "Mongolian food vs. your expectations",
    "Horse meat? Yak milk? Let’s go!",
    "Cooking Mongolian food like a pro",
    "The real Mongolian beef (not the fake one!)",
    "Milk tea, but make it Mongolian",
    "Steppe cuisine explained (kind of)",
    "Mongolian snacks you didn’t know you needed",
    "Why Mongolians love meat (a lot!)",
    "Mongolian feasts: go big or go home",
    "Avoiding food fails in Mongolia",
    "The art of drinking Airag without regrets",
    "Mongolian food hacks for travelers",
    "How to impress a Mongolian with your eating skills",
    "Festival foods worth traveling for",
    "Yak milk products—because why not?",
    "Mongolian breakfast: meat for breakfast?",
    "Best food markets in Ulaanbaatar",
    "Dried meat: Mongolia’s ultimate snack",
    "Mongolian cuisine vs. other Asian foods",
    "Mongolian meals that will test your stomach",
    "Unusual Mongolian foods (that you might love)",
    "Mongolian holiday foods to feast on",
    "Why nomads eat the way they do",
    "Mongolian cooking mistakes to avoid",
    "How to order food like a local",
    "The ultimate Mongolian food bucket list",
    "Fermented foods in Mongolia (not just for fun)",
    "How to prepare a Mongolian feast",
    "The truth about Mongolian meat obsession",
    "Genghis Khan’s diet (probably)",
    "Exotic Mongolian dishes you should try (or not)",
    "The one dish everyone in Mongolia eats",
    "Mongolian food culture: survive & thrive",
  ],
};

export default seoConfig;
