import { SeoType } from "@/types";

// This file contains the core meta data for the application
const seoConfig: SeoType = {
  title: "Mongol Food",
  subTitle: "Discover the Rich Flavors of Mongolian Cuisine",
  ogImage: "/images/mongol-food-opengraph.png",
  twitterImage: "/images/mongol-food-twitter.png",
  author: {
    name: "Tim Baz",
    twitterUrl: "https://x.com/timtbdev",
    twitterAddress: "@timtbdev",
    email: "timtb.dev@gmail.com",
  },
  description:
    "Explore the authentic taste of Mongolian food, from traditional dishes like Buuz and Khorkhog to modern Mongolian fusion cuisine.",
  tags: [
    "Mongolian food",
    "Traditional Mongolian cuisine",
    "Mongolian recipes",
    "Mongolian dishes",
    "Buuz Mongolian dumplings",
    "Khorkhog Mongolian BBQ",
    "Boodog roasted meat",
    "Bansh Mongolian soup dumplings",
    "Tsuivan stir-fried noodles",
    "Mongolian dairy products",
    "Aaruul dried curd",
    "Suutei tsai Mongolian milk tea",
    "Airag fermented mare’s milk",
    "Mongolian hot pot",
    "Mongolian street food",
    "Mongolian food culture",
    "How to cook Mongolian food",
    "Best Mongolian restaurants",
    "Mongolian food history",
    "Mongolian nomadic cuisine",
    "Mongolian beef recipes",
    "Mongolian lamb dishes",
    "Mongolian vegetarian food",
    "Mongolian cuisine ingredients",
    "Mongolian traditional drinks",
    "Mongolian food travel guide",
    "Nomadic food traditions",
    "Mongolian holiday foods",
    "Mongolian fusion cuisine",
    "How Mongolians eat meat",
    "Mongolian cooking techniques",
    "Authentic Mongolian food experience",
    "Mongolian food in Ulaanbaatar",
    "Mongolian home cooking",
    "Popular Mongolian foods",
    "Mongolian noodle dishes",
    "Dried meat in Mongolian cuisine",
    "Mongolian festival foods",
    "Easiest Mongolian recipes",
    "Traditional Mongolian snacks",
    "Mongolian cuisine vs. other Asian foods",
    "Steppe cuisine",
    "Mongolian food for travelers",
    "Mongolian cooking tips",
    "Mongolian kitchen essentials",
    "Health benefits of Mongolian food",
    "Mongolian food traditions",
    "Mongolian meat-based diet",
    "Fermented foods in Mongolia",
    "Mongolian dairy culture",
    "Mongolian street food guide",
    "Exotic Mongolian ingredients",
    "Mongolian meals for winter",
    "Mongolian feast preparation",
    "Yak milk products in Mongolia",
    "Horse meat in Mongolian food",
    "Cooking Mongolian food at home",
    "Mongolian breakfast dishes",
    "Unique Mongolian food facts",
    "Traditional Mongolian meal structure",
    "Food sustainability in Mongolia",
    "Famous Mongolian chefs",
    "Mongolian food blog",
    "Mongolian food documentary",
    "Must-try Mongolian dishes",
  ],
};

export default seoConfig;
